ALTER TABLE orders ADD COLUMN IF NOT EXISTS owner_platform_fee NUMERIC(10,2) DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS items_subtotal NUMERIC(10,2) DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS partner_commission NUMERIC(10,2) DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS calculated_distance_km NUMERIC(5,2) DEFAULT 0.00;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS customer_delivery_charge NUMERIC(10,2) DEFAULT 0.00;
